In [1]:
import numpy as np

#NumPy Arrays

In [4]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D Array
arr2 = np.array([[1, 2], [3, 4]])

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)
print("3D Array:\n", arr3)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2]
 [3 4]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#Array Attributes

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)       # Dimensions (rows, columns)
print("Size:", arr.size)         # Total number of elements
print("Data type:", arr.dtype)   # Data type of elements
print("Dimension:", arr.ndim)    # Number of dimensions


Shape: (2, 3)
Size: 6
Data type: int64
Dimension: 2


#Array Initialization

In [7]:
# Zeros
zeros = np.zeros((2, 3))  # 2 rows and 3 columns

# Ones
ones = np.ones((3, 2))  # 3 rows and 2 columns

# Identity Matrix
identity = np.eye(3)

# Random Values
random_array = np.random.rand(2, 3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Random Array:\n", random_array)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array:
 [[0.65753649 0.03121959 0.30358536]
 [0.63081835 0.55000988 0.53205816]]


#Array Indexing and Slicing

In [9]:
arr = np.array([10, 20, 30, 40, 50])
print("First Element:", arr[0])  # Access first element
print("Last Element:", arr[-1]) # Access last element
print("Slice:", arr[1:4])       # Elements from index 1 to 3


# For 2D arrays:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element [1, 2]:", matrix[1, 2]) # Row 1, Column 2
print("Row 1:", matrix[1, :])         # Entire row 1
print("Column 2:", matrix[:, 2])      # Entire column 2



First Element: 10
Last Element: 50
Slice: [20 30 40]
Element [1, 2]: 6
Row 1: [4 5 6]
Column 2: [3 6 9]


#Array Operations

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print("Addition:", arr1 + arr2)

# Multiplication
print("Multiplication:", arr1 * arr2)

# Dot Product
print("Dot Product:", np.dot(arr1, arr2))

# Transpose
matrix = np.array([[1, 2], [3, 4]])
print("Transpose:\n", matrix.T)


Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32
Transpose:
 [[1 3]
 [2 4]]


#Mathematical Functions

In [11]:
arr = np.array([1, 2, 3, 4])

# Sum
print("Sum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Standard Deviation
print("Std Dev:", np.std(arr))

# Minimum and Maximum
print("Min:", np.min(arr))
print("Max:", np.max(arr))


Sum: 10
Mean: 2.5
Std Dev: 1.118033988749895
Min: 1
Max: 4


#Reshaping Arrays

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped)


Reshaped Array:
 [[1 2 3]
 [4 5 6]]


#Filtering and Boolean Indexing

In [13]:
arr = np.array([1, 2, 3, 4, 5])
filtered = arr[arr > 3]  # Elements greater than 3
print("Filtered Array:", filtered)


Filtered Array: [4 5]


#Concatenation and Splitting

In [14]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Concatenate
concatenated = np.concatenate((arr1, arr2))
print("Concatenated:", concatenated)

# Splitting
split = np.array_split(concatenated, 2)
print("Splitted:", split)


Concatenated: [1 2 3 4]
Splitted: [array([1, 2]), array([3, 4])]


#Saving and Loading Arrays

In [15]:
arr = np.array([1, 2, 3, 4])

# Save
np.save('array.npy', arr)

# Load
loaded_array = np.load('array.npy')
print("Loaded Array:", loaded_array)


Loaded Array: [1 2 3 4]


#Random Number Generation

In [16]:
# Random Integers
rand_ints = np.random.randint(1, 10, size=(2, 3))

# Normal Distribution
normal = np.random.normal(loc=0, scale=1, size=5)

print("Random Integers:\n", rand_ints)
print("Normal Distribution:\n", normal)


Random Integers:
 [[8 3 4]
 [7 4 7]]
Normal Distribution:
 [0.73309407 0.57679662 1.41800327 1.53924508 0.37951356]


#Broadcasting
Rules of Broadcasting:
1. If the arrays differ in dimensions, prepend 1 to the smaller array's shape until they match.
Compare dimensions. Two dimensions are compatible if:
2. They are equal, or
One of them is 1.

In [17]:
a = np.array([1, 2, 3])          # Shape (3,)
b = np.array([[10], [20], [30]]) # Shape (3, 1)

# Broadcasting b to (3, 3)
result = a + b
print("Broadcasted Result:\n", result)


Broadcasted Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


#Advanced Indexing

In [19]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
result = arr[[0, 1, 2], [1, 2, 0]]  # Select elements (0,1), (1,2), (2,0)
print("Integer Indexing Result:", result)

# Boolean Indexing:
arr = np.array([10, 20, 30, 40, 50])
result = arr[arr > 25]  # Select elements greater than 25
print("Boolean Indexing Result:", result)



Integer Indexing Result: [20 60 70]
Boolean Indexing Result: [30 40 50]


#Structured Arrays

In [20]:
data = np.array([(1, 'Alice', 24.5), (2, 'Bob', 19.2)],
                dtype=[('id', 'i4'), ('name', 'U10'), ('score', 'f4')])

print("Structured Array:", data)
print("Names:", data['name'])  # Access 'name' column


Structured Array: [(1, 'Alice', 24.5) (2, 'Bob', 19.2)]
Names: ['Alice' 'Bob']


#Views and Copies

In [21]:
arr = np.array([10, 20, 30])
view = arr.view()
view[0] = 99
print("Original Array:", arr)



'''Copy:
A deep copy creates a new array. Changes do not affect the original.'''

copy = arr.copy()
copy[0] = 77
print("Original Array After Copy Modification:", arr)


Original Array: [99 20 30]
Original Array After Copy Modification: [99 20 30]


#Stacking and Splitting Arrays

In [23]:
a = np.array([1, 2])
b = np.array([3, 4])

# Vertical Stack
v_stack = np.vstack((a, b))

# Horizontal Stack
h_stack = np.hstack((a, b))

print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)


# Splitting:
arr = np.array([1, 2, 3, 4, 5, 6])
split = np.array_split(arr, 3)
print("Split Result:", split)



Vertical Stack:
 [[1 2]
 [3 4]]
Horizontal Stack:
 [1 2 3 4]
Split Result: [array([1, 2]), array([3, 4]), array([5, 6])]


#Sorting and Searching

In [24]:
arr = np.array([30, 10, 20])
sorted_arr = np.sort(arr)  # Returns a sorted copy
print("Sorted Array:", sorted_arr)


# Searching for Values:
arr = np.array([10, 20, 30, 40])
indices = np.where(arr > 25)  # Indices where condition is True
print("Indices:", indices)


Sorted Array: [10 20 30]
Indices: (array([2, 3]),)


#Linear Algebra with NumPy

In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)  # or np.matmul(a, b)
print("Matrix Multiplication:\n", result)


Matrix Multiplication:
 [[19 22]
 [43 50]]


#Determinant and Inverse:

In [26]:
matrix = np.array([[1, 2], [3, 4]])

# Determinant
det = np.linalg.det(matrix)

# Inverse
inverse = np.linalg.inv(matrix)

print("Determinant:", det)
print("Inverse:\n", inverse)


Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


#Statistical Functions

In [28]:
# percentile
arr = np.array([10, 20, 30, 40, 50])
percentile = np.percentile(arr, 50)  # 50th percentile (median)
print("50th Percentile:", percentile)


# Correlation and Covariance:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Correlation Coefficient
corr = np.corrcoef(x, y)

# Covariance Matrix
cov = np.cov(x, y)

print("Correlation Coefficient:\n", corr)
print("Covariance Matrix:\n", cov)



50th Percentile: 30.0
Correlation Coefficient:
 [[1. 1.]
 [1. 1.]]
Covariance Matrix:
 [[1. 1.]
 [1. 1.]]


#Memory Management

In [29]:
# Change Data Type:


arr = np.array([1, 2, 3], dtype='int64')
print("Original Data Type:", arr.dtype)

arr = arr.astype('int32')  # Convert to smaller data type
print("Converted Data Type:", arr.dtype)
# View Memory Layout:

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Memory Layout:\n", arr.flags)

Original Data Type: int64
Converted Data Type: int32
Memory Layout:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



#Broadcasting in Operations


In [30]:
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])

# Broadcasting to add vector to each row
result = matrix + vector
print("Broadcasting Result:\n", result)


Broadcasting Result:
 [[11 22]
 [13 24]]
